# Generated by Django 5.2.7 on 2025-10-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('website', models.URLField(blank=True)),
                ('category', models.CharField(choices=[('restaurant', 'Restaurant'), ('club', 'Club'), ('real_estate', 'Agenzia Immobiliare'), ('travel_agency', 'Agenzia Viaggi'), ('medical', 'Studio Medico'), ('technical_studio', 'Studio Tecnico'), ('dentist', 'Dentista'), ('physiotherapist', 'Fisioterapista'), ('private_school', 'Scuola Privata'), ('beauty_center', 'Centro Estetico'), ('artisan', 'Artigiano'), ('other', 'Altro')], max_length=64)),
                ('country', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['country', 'city', 'category'], name='businesses__country_359a30_idx')],
            },
        ),
    ]
