# Generated by Django 5.2.7 on 2025-10-16 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('email_generation', 'Email Generation'), ('bulk_email', 'Bulk Email Template'), ('business_search', 'Business Search'), ('gemini_test', 'Gemini Test')], help_text='Type of AI request made', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current status of the request', max_length=20)),
                ('request_data', models.JSONField(blank=True, default=dict, help_text='Input data for the AI request')),
                ('response_data', models.JSONField(blank=True, default=dict, help_text='Response data from the AI service')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who made the request (null for anonymous requests)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Request',
                'verbose_name_plural': 'AI Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
